version: '3.9'

services:
  app:
    build:
      context: ./docker/php        # ← ここをDockerfileのあるディレクトリに
      dockerfile: Dockerfile       # ← 明示指定（任意だが可読性UP）
    container_name: php-app
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin8082
    environment:
      PMA_HOST: db
      PMA_USER: sample_user
      PMA_PASSWORD: sample_pass
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  db_data:
