version: '3.9'

services:
  app:
    build:
      context: ./docker/php        # Dockerfile のあるディレクトリ
      dockerfile: Dockerfile       # ← 明示的に指定
    container_name: php-app
    ports:
      - "8080:80"                  # PHP/Apache → http://localhost:8080
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin8081
    environment:
      PMA_HOST: db
      PMA_USER: admin_user         # ← 変更
      PMA_PASSWORD: admin_pass     # ← 変更
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
