openapi: 3.0.3
info:
  title: FlashCard Backend API
  version: 1.0.0
  description: API documentation for FlashCard backend
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/example:
    get:
      summary: Example endpoint
      description: サンプルのGET API
      responses:
        '200':
          description: 成功時のレスポンス
